---

apt_packages:
  - aptitude
  - bbswitch-dkms
  - build-essential
  - checkinstall
  - chromium-browser
  - cmake
  - compton
  - curl
  - dkms
  - feh
  - font-manager
  - fonts-font-awesome
  - gadmin-openvpn-client
  - gengetopt
  - git
  - gnome-terminal
  - golang
  - gvfs-bin
  - htop
  - i3
  - i3blocks
  - imagemagick
  - libc6-dev
  - libffi-dev
  - libgdbm-dev
  - libice-dev
  - libjansson4
  - libncursesw5-dev
  - libpthread-stubs0-dev
  - libsm-dev
  - libsqlite3-dev
  - libssl-dev
  - libssl-doc
  - libtinfo-dev
  - libx11-dev
  - libx11-doc
  - libxau-dev
  - libxcb1-dev
  - libxdmcp-dev
  - libxext-dev
  - libxnvctrl0
  - libxrender-dev
  - libxss-dev
  - libxt-dev
  - lynx
  - openvpn
  - pandoc
  - pavucontrol
  - powerline
  - powertop
  - pulseaudio
  - pwgen
  - python3-pip
  - python3-setuptools
  - python3-venv
  - python-all
  - python-pip
  - rar
  - rofi
  - screenfetch
  - screen-resolution-extra
  - smartmontools
  - sshpass
  - tcl
  - thunar
  - tk
  - tk-dev
  - uuid-dev
  - vim
  - virtualenv
  - virtualenvwrapper
  - volumeicon-alsa
  - whois
  - xpdf
  - xserver-xorg-legacy
  - xtrans-dev
  - zlib1g-dev
  - zsh
  - nmap
